# Generated by Django 5.2.6 on 2025-09-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fechaPago',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
