# Generated by Django 5.2.6 on 2025-09-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_direccion_alter_pago_fechapago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='documento',
            field=models.IntegerField(blank=True, default=None, null=True, unique=True),
        ),
    ]
